/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
//#include <stm32f4xx.h>

void UART2_Init(void)
{
	//Enable clock for GPIOA (where UART TX pin is located)
	RCC -> AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

	//Set PA2 (USART TX pin) as alternate function
	GPIOA->MODER &= ~(3 <<(2*2)); //Clear mode bits for PA2
	GPIO->MODER |= (2<<(2*2)); // Set PA2 t alternate function mode
	GPIO->AFR[0] |= (7<<(2*4)); // Set PA2 to AF7 (USART2)

	//Enable Clock for USART2
	RCC-> APB1ENR |= RCC_APB1ENR_USART2EN;

	// Configure USART2
	USART2->CR1 &= ~USART_CR1_UE; // Disable USART2
	USART2->BRR = 0x1A0; // Set baud rate to 115200 (assuming 84 Mhz clock)
	USART2->CR1 |= USART_CR1_TE; // Enable transmitter
	USART2-> CR1 |= USART_CR1_UE; // Enable USART2
}

void UART2_SendChar(char c)
{
	while(!(USART2->SR & USART_SR_TXE)); //Loop runs till the transmit data register is empty,
	// then it moves to the next line
	USART2->DR = c;
}

void UART2_SendString(char *str)
{
	while(*str)
		UART2_SendChar(str++); //Send each character in the string
}



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    //Initialize the UART
	UART2_Init();

	//Send 'Hello World' over UART to your PC
	UART2_SendString("Hello World!\\r\\n");

	while(1)
	{

	}
}
